### ISSUE TITLE
run test voc2007 error.

### ISSUE THREAD

**Issue by 10183308** [dvornikita/blitznet#1]
hi， 
 when run the command: 
python test.py --run_name=BlitzNet512_COCO --dataset=voc07 --split=test --image_size=512 --detect --segment --ckpt=1

it show errors:

 shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.694924: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.695087: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.695199: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.695386: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.695567: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.695809: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.695970: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.696142: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.696327: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.696403: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.696473: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.696734: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
2017-08-23 18:41:49.696875: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]
Traceback (most recent call last):
  File "test.py", line 113, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test.py", line 62, in main
    detector.restore_from_ckpt(args.ckpt)
  File "/media/media_share/linkfile/blitznet/blitznet/detector.py", line 107, in restore_from_ckpt
    saver.restore(self.sess, ckpt_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]

Caused by op u'save/Assign_279', defined at:
  File "test.py", line 113, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test.py", line 62, in main
    detector.restore_from_ckpt(args.ckpt)
  File "/media/media_share/linkfile/blitznet/blitznet/detector.py", line 106, in restore_from_ckpt
    saver = tf.train.Saver(tf.global_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 271, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [81]
         [[Node: save/Assign_279 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_7/biases, save/RestoreV2_279/_1)]]

Could you give me some adivce?

thank you very much

**Comment by dvornikita** [comment]
The error is caused by the fact that you load a checkpoint for a model trained on Microsoft COCO that has 80 + 1 categories, but you test it on the VOC07 dataset that has 20 + 1 categories. Specify another run_name when testing on VOC, e.g.  --run_name=BlitzNet512_COCO+VOC07+12 or --run_name=BlitzNet512_VOC07+12.

Note that in this run the flag --segment will not have any effect since there are no segmentation annotations for VOC07 and this command will only evaluate the detection metrics. However, you can drop the estimated segmentations in the results folder by specifying the flag --save_first_n=K, where K defines first K images in the evaluation list. If K is greater than the dataset size, all the images will be dropped with their visualizations.

Don't hesitate to contact if something else goes wrong.
