### ISSUE TITLE
an errors when training on pascal voc dataset

### ISSUE THREAD

**Issue by Engineering-Course** [dvornikita/blitznet#13]
I train the network on Pascal VOC dataset.
The training progresses well at the beginning.  But an error occurs after thousands of iterations.
If I restart training, the same error will occur again after thousands of iterations.
It seems that it is caused by the gradient or loss. 
Could you please take a look and help me fix it up?
Thanks.

`
2017-10-10 11:53:49.895995: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.896694: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.897436: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.901151: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.901662: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.915369: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.915371: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.915423: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.915459: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
2017-10-10 11:53:49.916251: W tensorflow/core/kernels/queue_base.cc:295] _3_shuffle_batch/random_shuffle_queue: Skipping cancelled enqueue attempt with queue not closed
2017-10-10 11:53:49.916323: W tensorflow/core/kernels/queue_base.cc:295] _3_shuffle_batch/random_shuffle_queue: Skipping cancelled enqueue attempt with queue not closed
2017-10-10 11:53:49.916366: W tensorflow/core/kernels/queue_base.cc:295] _0_parallel_read/filenames: Skipping cancelled enqueue attempt with queue not closed
2017-10-10 11:53:49.916420: W tensorflow/core/kernels/queue_base.cc:295] _2_parallel_read/common_queue: Skipping cancelled enqueue attempt with queue not closed
2017-10-10 11:53:49.916468: W tensorflow/core/kernels/queue_base.cc:295] _3_shuffle_batch/random_shuffle_queue: Skipping cancelled enqueue attempt with queue not closed
2017-10-10 11:53:49.916490: W tensorflow/core/kernels/queue_base.cc:295] _3_shuffle_batch/random_shuffle_queue: Skipping cancelled enqueue attempt with queue not closed
2017-10-10 11:53:49.916524: W tensorflow/core/kernels/queue_base.cc:295] _2_parallel_read/common_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.CancelledError'>, Enqueue operation was cancelled
         [[Node: parallel_read/filenames/filenames_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/filenames, parallel_read/filenames/RandomShuffle)]] 
 File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
`

`
[INFO]: Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.CancelledError'>, Enqueue operation was cancelled
         [[Node: parallel_read/filenames/filenames_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/filenames, parallel_read/filenames/RandomShuffle)]]
    return fn(*args)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
         [[Node: train_op/control_dependency/_879 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_18944
_train_op/control_dependency", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

`
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "training_person_edge.py", line 364, in <module>
    tf.app.run()
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "training_person_edge.py", line 348, in main
    train(dataset, net, net_config)
  File "training_person_edge.py", line 292, in train
    train_loss, acc, iou, _, lr = sess.run([train_op, train_acc, mean_iou, update_mean_iou, learning_rate])
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
         [[Node: train_op/control_dependency/_879 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_18944
_train_op/control_dependency", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

`
Caused by op 'gradients/TopKV2_grad/Reshape', defined at:
  File "training_person_edge.py", line 364, in <module>
    tf.app.run()
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "training_person_edge.py", line 348, in main
    train(dataset, net, net_config)
  File "training_person_edge.py", line 253, in train
    summarize_gradients=True)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 440, in create_train_op
    check_numerics=check_numerics)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/training/python/training/training.py", line 439, in create_train_op
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 542, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 348, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 542, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/nn_grad.py", line 707, in _TopKGrad
    ind_2d = array_ops.reshape(op.outputs[1], array_ops.stack([-1, ind_lastdim]))
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in reshape
    name=name)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
`

`
...which was originally created as op 'TopKV2', defined at:
  File "training_person_edge.py", line 364, in <module>
    tf.app.run()
[elided 1 identical lines from previous traceback]
  File "training_person_edge.py", line 348, in main
    train(dataset, net, net_config)
  File "training_person_edge.py", line 219, in train
    seg_logits, seg_gt, edge_logits, edge_gt, dataset, config)
  File "training_person_edge.py", line 153, in objective
    detection_loss(location, confidence, refine_ph, classes_ph, pos_mask)
  File "training_person_edge.py", line 106, in detection_loss
    number_of_negatives)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1949, in top_k
    return gen_nn_ops._top_kv2(input, k=k, sorted=sorted, name=name)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2577, in _top_kv2
    name=name)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/gongke/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
`

`
InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_835, gradients/TopKV2_grad/stack)]]
         [[Node: train_op/control_dependency/_879 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_18944
_train_op/control_dependency", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

**Comment by dvornikita** [comment]
Check the last comments of #5. I guess your batch is too small.

**Comment by Engineering-Course** [comment]
I set the batch size to 4 because of the limitation of GPU memory.
I agree that it is caused by data augmentation when the random crop doesn't contain an object.
I find that the function `tf.image.sample_distorted_bounding_box` is used to generate distorted bounding boxes and the min_object_covered is set to [0.0, 0.1, 0.3, 0.5, 0.7, 0.9] (sample_jaccards).
Is it necessary to set the min_object_covered to 0.0?  Is it works for this error if 0.0 is removed from the sample_jaccards array?
I think the object-missing crop will still exist but the probability will decrease.

`    
for iou in params['sample_jaccards']:
        sample_distorted_bounding_box = tf.image.sample_distorted_bounding_box(
            tf.shape(image),
            bounding_boxes=bboxes,
            min_object_covered=iou,
            aspect_ratio_range=[0.5, 2.0],
            area_range=[0.3, 1.0],
            max_attempts=params['crop_max_tries'],
            use_image_if_no_bounding_boxes=True)
        samplers.append(sample_distorted_bounding_box[:2])
        boxes.append(sample_distorted_bounding_box[2][0][0])
`

`
data_augmentation_config = {
    'X_out': 4,
    'brightness_prob': 0.5,
    'brightness_delta': 0.125,
    'contrast_prob': 0.5,
    'contrast_delta': 0.5,
    'hue_prob': 0.5,
    'hue_delta': 0.07,
    'saturation_prob': 0.5,
    'saturation_delta': 0.5,
    'sample_jaccards': [0.0, 0.1, 0.3, 0.5, 0.7, 0.9],
    'flip_prob': 0.5,
    'crop_max_tries': 50,
    'zoomout_color': [x/255.0 for x in reversed(MEAN_COLOR)],
}
`

**Comment by dvornikita** [comment]
For data augmentation, we followed the strategy of SSD paper. We didn't evaluate the cases of constraining sampling in this way. You can see some evaluations in the original [paper](https://arxiv.org/abs/1512.02325).
What you can do is to not make a forward pass in case you have no positives. This would require minimum modifications in the code.

**Comment by Engineering-Course** [comment]
I checked the code in training.py.
if number_of_positives is zere, then number_of_negatives will become zero which may cause an error in  tf.nn.top_k function. 
Dose it work that a line is appened to set number_of_negatives at least one?

`    
 def detection_loss(location, confidence, refine_ph, classes_ph, pos_mask):
        neg_mask = tf.logical_not(pos_mask)
        number_of_positives = tf.reduce_sum(tf.to_int32(pos_mask))
        number_of_negatives = tf.minimum(3 * number_of_positives,
                                        tf.shape(pos_mask)[1] - number_of_positives)
        normalizer = tf.to_float(tf.add(number_of_positives, number_of_negatives))
        tf.summary.scalar('batch/size', normalizer)
        num_pos_float = tf.to_float(number_of_positives)

        cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=confidence,
                                                                       labels=classes_ph)
        pos_class_loss = tf.reduce_sum(tf.boolean_mask(cross_entropy, pos_mask))
        tf.summary.scalar('loss/class_pos', pos_class_loss / num_pos_float)

        top_k_worst, top_k_inds = tf.nn.top_k(tf.boolean_mask(cross_entropy, neg_mask),
                                            number_of_negatives)
        neg_class_loss = tf.reduce_sum(top_k_worst)
        class_loss = (neg_class_loss + pos_class_loss) / num_pos_float
        tf.summary.scalar('loss/class_neg', neg_class_loss / tf.to_float(number_of_negatives))
        tf.summary.scalar('loss/class', class_loss)
`

**Comment by dvornikita** [comment]
Sorry, I didn't get you question.

**Comment by fastlater** [comment]
@Engineering-Course  I commented this issue and I was waiting to get my new gpu so I could continue testing using a higher batch size. However, in the meanwhile I tried with learning rate = 0 and batch_size = 1 and this error still coming out. @dvornikita  Does it means that this error will come out if the batch size is not large enough? Does the code could be change a little to skip this error as mentioned @Engineering-Course ? I understand that batch size = 1 will have this error normally but batch size = 4 should get at least a non error result.

**Comment by Engineering-Course** [comment]
If the batch size is small, it is more likely that the random cropped batch doesn't contain any objects, which means there are no positive samples. 
When it happens, the number_of_positives is zero.
        number_of_positives = tf.reduce_sum(tf.to_int32(pos_mask))
Then number_of_negatives becomes zero too.
        number_of_negatives = tf.minimum(3 * number_of_positives,
                                        tf.shape(pos_mask)[1] - number_of_positives)
It will thus cause an error in tf.nn.top_k function.
        top_k_worst, top_k_inds = tf.nn.top_k(tf.boolean_mask(cross_entropy, neg_mask),
                                            number_of_negatives)
So I recommand to appened a line to set number_of_negatives at least one before calling tf.nn.top_k function.
        number_of_negatives = tf.maximum(1, number_of_negatives)

These codes are in `detection_loss` function in training.py

**Comment by fastlater** [comment]
@Engineering-Course  let me know when you test it, and if you overcome the error. I cannot do it by myself because my gpu is not good and I cannot even set batch size to 2. I will get my gpu in a few weeks so till them, I cannot test.

**Comment by Engineering-Course** [comment]
You can try it even when batch size is 1. It works for me.

**Comment by dvornikita** [comment]
@fastlater, The solution of @Engineering-Course should work fine. Just note that in this case you learn from only one negative example, normalizing the loss by one, which gives the loss of the same order of magnitude as usual but the signal is not very desirable. This might bias the training, especially if this situation comes up often. So in addition to that, I would multiply the loss by zero if this occurs.

**Comment by Engineering-Course** [comment]
Yes. Agree with you.

**Comment by fastlater** [comment]
@dvornikita @Engineering-Course  Thank you for feedback.

**Comment by dvornikita** [comment]
Pushed that modification. You can test it.

**Comment by fastlater** [comment]
@dvornikita @Engineering-Course  I tried it just for testing with batch_size=1, and the error now is the Nan in summary histogram for: summarize_grads/ssd/confidence/ssd_back/block_rev2/weights_gradiant. This error came out when you tested the code?

**Comment by dvornikita** [comment]
@fastlater I fixed this in the last commit. Apparently, the error was caused by bbox_loss since it uses the smooth l1 loss that also breaks with no positives. Now the training doesn't break but I didn't manage to make it learn something meaningful with the batch size of 1, which is not so surprising.

**Comment by fastlater** [comment]
@dvornikita As we all expected, it wont learn something meaningful. However, it was good to fix it.

**Comment by dvornikita** [comment]
@clxia12 It's in the root folder of the project
