### ISSUE TITLE
Run demo with dataset voc07+12 only?

### ISSUE THREAD

**Issue by aureosun** [dvornikita/blitznet#27]
Hello,@dvornikita,I'm interested in your work,and after read your paper,I decide to run your demo,but I encounter the problem below,could you please help me?
My tensorflow is  '1.5.0-dev20171114'
my opencv version is 3.3.0,
python version is anaconda2
I download the voc2007 and voc2012 dataset,and put them at /home/datasets after run and I comment the datasets.py #from coco_loader import COCOLoader, COCO_CATS and uncomment the main function about voc dataset,after run datasets.py,I got the traceback:

5000 files are processed
Done
Traceback (most recent call last):
  File "datasets.py", line 239, in <module>
    create_voc_dataset('12', 'train', True, True)
  File "datasets.py", line 210, in create_voc_dataset
    loader = VOCLoader(year, split, segmentation=segmentation, augmented_seg=augmented_seg)
  File "/home/winter/blitznet/voc_loader.py", line 46, in __init__
    with open(os.path.join(self.root, filelist % self.split), 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/winter/Datasets/VOCdevkit/VOC2012/ImageSets/SegmentationAug/train.txt'

I guess this is because I didn't use extra annotations for segmentation provided by B. Hariharan et al,
then I go on to run the demo,I have downloaded BlitzNet300* and BlitzNet500* that for voc07+12 datasets,after run 
python demo.py --run_name=BlitzNet300_VOC07+12 --x4 --detect --segment --eval_min_conf=0.5 --ckpt=1
I got the error:

Traceback (most recent call last):
  File "demo.py", line 69, in <module>
    tf.app.run()
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 58, in main
    detector.restore_from_ckpt(args.ckpt)
  File "/home/winter/blitznet/detector.py", line 111, in restore_from_ckpt
    saver.restore(self.sess, ckpt_path)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_270 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_2/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_2/weights, save/RestoreV2_270/_23)]]

Caused by op u'save/Assign_270', defined at:
  File "demo.py", line 69, in <module>
    tf.app.run()
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 58, in main
    detector.restore_from_ckpt(args.ckpt)
  File "/home/winter/blitznet/detector.py", line 110, in restore_from_ckpt
    saver = tf.train.Saver(tf.global_variables())
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 271, in assign
    validate_shape=validate_shape)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/winter/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_270 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_2/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv_2/weights, save/RestoreV2_270/_23)]]

I'm confusing about this ,could you help me? Thank you

**Comment by dvornikita** [comment]
I see what's going on. Most likely you need to run it with the flag --seg_filter_size=3. The graph is built with this value set to 1 by default.

**Comment by dvornikita** [comment]
Closing due to lack of recent activity.
