### ISSUE TITLE
python demo.py --run_name=BlitzNet300_COCO+VOC07+12 --x4 --detect --segment --eval_min_conf=0.5 --ckpt=1

### ISSUE THREAD

**Issue by ghost** [dvornikita/blitznet#41]
python demo.py --run_name=BlitzNet300_COCO+VOC07+12 --x4 --detect --segment --eval_min_conf=0.5 --ckpt=1

Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
WARNING:tensorflow:From /home/cbl/PycharmProjects/blitznet-master/resnet.py:136: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead

however,found nothing change in the demodemo/output

**Comment by dvornikita** [comment]
What is the problem here?

**Comment by EchoAmor** [comment]
@chenbolinstudent  I have met the same problem like yours! can you tell me how to solve this? I want to test my own pictures and get results,how to do so ?thanks a lot !!!! @dvornikita

**Comment by dvornikita** [comment]
But what is the error message you are receiving?

**Comment by EchoAmor** [comment]
`/home/echo/anaconda3/envs/Blitznet/bin/python /home/echo/a_project/blitznet/demo.py --run_name=BlitzNet300_COCO --x4 --segment --eval_min_conf=0.5 --ckpt=1`

The error message is :

`2019-07-01 09:47:02.995633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-07-01 09:47:08.603265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-01 09:47:08.603312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-07-01 09:47:08.603326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-07-01 09:47:08.612055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11313 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_266 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd/Conv/weights, save/RestoreV2/_533)]]
	 [[Node: save/RestoreV2/_792 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_798_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:396)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1725, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_266 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd/Conv/weights, save/RestoreV2/_533)]]
	 [[Node: save/RestoreV2/_792 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_798_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:396)]]

Caused by op 'save/Assign_266', defined at:
  File "/home/echo/a_project/blitznet/demo.py", line 68, in <module>
    tf.app.run()
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/echo/a_project/blitznet/demo.py", line 57, in main
    detector.restore_from_ckpt(args.ckpt)
  File "/home/echo/a_project/blitznet/detector.py", line 110, in restore_from_ckpt
    saver = tf.train.Saver(tf.global_variables())
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 112, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 216, in assign
    validate_shape=validate_shape)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_266 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd/Conv/weights, save/RestoreV2/_533)]]
	 [[Node: save/RestoreV2/_792 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_798_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:396)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/echo/a_project/blitznet/demo.py", line 68, in <module>
    tf.app.run()
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/echo/a_project/blitznet/demo.py", line 57, in main
    detector.restore_from_ckpt(args.ckpt)
  File "/home/echo/a_project/blitznet/detector.py", line 111, in restore_from_ckpt
    saver.restore(self.sess, ckpt_path)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1759, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_266 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd/Conv/weights, save/RestoreV2/_533)]]
	 [[Node: save/RestoreV2/_792 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_798_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:396)]]

Caused by op 'save/Assign_266', defined at:
  File "/home/echo/a_project/blitznet/demo.py", line 68, in <module>
    tf.app.run()
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/echo/a_project/blitznet/demo.py", line 57, in main
    detector.restore_from_ckpt(args.ckpt)
  File "/home/echo/a_project/blitznet/detector.py", line 110, in restore_from_ckpt
    saver = tf.train.Saver(tf.global_variables())
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 112, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 216, in assign
    validate_shape=validate_shape)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/echo/anaconda3/envs/Blitznet/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
	 [[Node: save/Assign_266 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd/Conv/weights, save/RestoreV2/_533)]]
	 [[Node: save/RestoreV2/_792 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_798_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:396)]`

**Comment by dvornikita** [comment]
I see what is going on. Run the same command with an additional flag --seg_filter_size=3
That should help.

**Comment by EchoAmor** [comment]
I just tried,but it didn't work ,the error message is:

`InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,448,21] rhs shape= [3,3,448,81]
	 [[Node: save/Assign_280 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv_7/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ssd/Conv_7/weights, save/RestoreV2/_561)]]
	 [[Node: save/RestoreV2/_802 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_808_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:401)]]
`

**Comment by dvornikita** [comment]
Oh, I see now. You are using the wrong model name. Instead of --run_name=BlitzNet300_COCO there should be --run_name=BlitzNet300_COCO+VOC07+12

Follow the readme and everything should work
