### ISSUE TITLE
Demo results

### ISSUE THREAD

**Issue by madhu-korada** [dvornikita/blitznet#51]
There are no results stored after the demo file has been executed.
input:
python demo.py --run_name=BlitzNet300_COCO+VOC07+12 --x4 --detect --segment --eval_min_conf=0.5 --ckpt=1

output:
2019-02-12 16:50:43.588949: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-12 16:50:43.798149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2019-02-12 16:50:43.807290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-02-12 16:50:44.757899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-12 16:50:44.762746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-02-12 16:50:44.766075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-02-12 16:50:44.770290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6387 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)

Processing C:\Users\madhu\Desktop\working\blitznet-master\demodemo\000456.jpg
Traceback (most recent call last):
  File "demo.py", line 68, in <module>
    tf.app.run()
  File "D:\Users\madhu\Anaconda3\envs\blitznet\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "demo.py", line 63, in main
    seg_gt=None, gt_bboxes=None, gt_cats=None)
  File "C:\Users\madhu\Desktop\working\blitznet-master\detector.py", line 248, in feed_forward
    name, draw=draw)
  File "C:\Users\madhu\Desktop\working\blitznet-master\detector.py", line 213, in process_detection
    self.draw(img, dets, cats, scores, name, gt_bboxes, gt_cats)
  File "C:\Users\madhu\Desktop\working\blitznet-master\detector.py", line 85, in draw
    args.eval_min_conf)), 'JPEG')
  File "D:\Users\madhu\Anaconda3\envs\blitznet\lib\site-packages\PIL\Image.py", line 1991, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'C:\\Users\\madhu\\Desktop\\working\\blitznet-master\\demodemo\\output/C:\\Users\\madhu\\Desktop\\working\\blitznet-master\\demodemo\\000456_det_50.jpg'

what is the problem here?

**Comment by min0628** [comment]
Modify 'demo.py', line 50

Before.
loader = Loader(osp.join(EVAL_DIR, 'demodemo'))

After
loader = Loader(osp.join(EVAL_DIR, 'Demo'))

**Comment by dvornikita** [comment]
Hi, @madhu-korada, as @min0628 mentioned should solve the problem indeed.
Thanks @min0628.
